version: '3.8'
services:
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - ../../scripts:/scripts

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mailer:
    image: adidas-subscription-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/home/node/app
    command: yarn workspace mailer dev
    environment:
      KAFKA_URL: ${KAFKA_URL}

  subscription:
    image: adidas-subscription-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/home/node/app
    depends_on:
      - mongo

    command: yarn workspace subscription dev
    environment:
      MONGO_URL: ${MONGO_URL}
      PORT: 80

  public-api:
    image: adidas-subscription-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/home/node/app
    depends_on:
      - subscription
    command: yarn workspace public-api dev
    environment:
      PORT: 80
      SUBSCRIPTION_URL: ${SUBSCRIPTION_URL}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_URL: ${KAFKA_URL}

  private-api:
    image: adidas-subscription-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/home/node/app
    depends_on:
      - subscription
    command: yarn workspace private-api dev
    environment:
      PORT: 80
      SUBSCRIPTION_URL: ${SUBSCRIPTION_URL}
      MAILER: ${MAILER_URL}
      JWT_SECRET: ${JWT_SECRET}



  e2e:
    image: adidas-subscription-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/home/node/app
    depends_on:
      - public-api
      - private-api

    command: yarn workspace e2e test --watch
    environment:
      MONGO_URL:  ${MONGO_URL}
      SUBSCRIPTION_URL: ${SUBSCRIPTION_URL}
      MAILER: ${MAILER_URL}
      JWT_SECRET: ${JWT_SECRET}
      SUBSCRIPTION_PRIVATE_API_URL: ${SUBSCRIPTION_PRIVATE_API_URL}
      SUBSCRIPTION_PUBLIC_API_URL: ${SUBSCRIPTION_PUBLIC_API_URL}

    